# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: |
          $(dockerHub)
        repository: $(imageName)
        command: push
        tags: |
          $(tag)

#steps:
#- bash: |
#    #docker build -t deepspeed:latest -f Dockerfile .
#    #docker tag deepspeed:latest deepspeed/deepspeed:latest
#    echo "env:$MY_TOKEN" | docker login --username deepspeed --password-stdin
#    echo "$? done"
#    #docker push deepspeed/deepspeed:latest
#  env:
#    MY_TOKEN: $TOKEN
