# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: docker login --username deepspeed --password $MYSECRET
    env:
      MySecret: $(TOKEN)

#steps:
#- bash: |
#    #docker build -t deepspeed:latest -f Dockerfile .
#    #docker tag deepspeed:latest deepspeed/deepspeed:latest
#    echo "env:$MY_TOKEN" | docker login --username deepspeed --password-stdin
#    echo "$? done"
#    #docker push deepspeed/deepspeed:latest
#  env:
#    MY_TOKEN: $TOKEN
